In [1]:
import re
import numpy as np
from PIL import Image

In [2]:
print("Huffman Compression Program")
print("=================================================================")
def get_num_pixels(filepath):
    width, height = Image.open(filepath).size
    return width*height
h = int(input("Enter 1 if you want to input an colour image file, 2 for default gray scale case:"))
if h == 1:
    file = input("Enter the filename:")
    num_pixels=get_num_pixels(file)
    my_string = np.asarray(Image.open(file),np.uint8)
    shape = my_string.shape
    print(shape)
    a = my_string
    print ("Entered string is:",my_string)
    my_string = str(my_string.tolist())
elif h == 2:
    array = np.arange(0, 737280, 1, np.uint8)
    my_string = np.reshape(array, (1024, 720))
    num_pixels=737280
    print ("Entered string is:",my_string)
    a = my_string
    my_string = str(my_string.tolist())

else:
    print("You entered invalid input")                    # taking user input

Huffman Compression Program
Enter 1 if you want to input an colour image file, 2 for default gray scale case:1
Enter the filename:man.jpg
(275, 183, 3)
Entered string is: [[[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 ...

 [[10 10 10]
  [ 6  6  6]
  [ 3  3  3]
  ...
  [ 4  4  4]
  [ 5  5  5]
  [ 5  5  5]]

 [[10 10 10]
  [ 6  6  6]
  [ 3  3  3]
  ...
  [ 4  4  4]
  [ 5  5  5]
  [ 5  5  5]]

 [[10 10 10]
  [ 6  6  6]
  [ 3  3  3]
  ...
  [ 4  4  4]
  [ 5  5  5]
  [ 5  5  5]]]


In [3]:
letters = []
only_letters = []
for letter in my_string:
    if letter not in letters:
        frequency = my_string.count(letter)             #frequency of each letter repetition
        letters.append(frequency)
        letters.append(letter)
        only_letters.append(letter)

nodes = []
while len(letters) > 0:
    nodes.append(letters[0:2])
    letters = letters[2:]                               # sorting according to frequency
nodes.sort()
huffman_tree = []
huffman_tree.append(nodes)                             #Make each unique character as a leaf node

In [4]:
def combine_nodes(nodes):
    pos = 0
    newnode = []
    if len(nodes) > 1:
        nodes.sort()
        nodes[pos].append("1")                       # assigning values 1 and 0
        nodes[pos+1].append("0")
        combined_node1 = (nodes[pos] [0] + nodes[pos+1] [0])
        combined_node2 = (nodes[pos] [1] + nodes[pos+1] [1])  # combining the nodes to generate pathways
        newnode.append(combined_node1)
        newnode.append(combined_node2)
        newnodes=[]
        newnodes.append(newnode)
        newnodes = newnodes + nodes[2:]
        nodes = newnodes
        huffman_tree.append(nodes)
        combine_nodes(nodes)
    return huffman_tree                                     # huffman tree generation

In [5]:
newnodes = combine_nodes(nodes)

huffman_tree.sort(reverse = True)
print("Huffman tree with merged pathways:")

checklist = []
for level in huffman_tree:
    for node in level:
        if node not in checklist:
            checklist.append(node)
        else:
            level.remove(node)
count = 0
for level in huffman_tree:
    print("Level", count,":",level)             #print huffman tree
    count+=1
print()

letter_binary = []
if len(only_letters) == 1:
    lettercode = [only_letters[0], "0"]
    letter_binary.append(lettercode*len(my_string))
else:
    for letter in only_letters:
        code =""
        for node in checklist:
            if len (node)>2 and letter in node[1]:           #genrating binary code
                code = code + node[2]
        lettercode =[letter,code]
        letter_binary.append(lettercode)
print(letter_binary)
print("Binary code generated:")
for letter in letter_binary:
    print(letter[0], letter[1])

bitstring =""
for character in my_string:
    for item in letter_binary:
        if character in item:
            bitstring = bitstring + item[1]
binary ="0b"+bitstring
print("Your message as binary is:",binary)
                                        # binary code generated


Huffman tree with merged pathways:
Level 0 : [[656322, ' ,7016543[]298']]
Level 1 : [[301948, ' ,', '1'], [354374, '7016543[]298', '0']]
Level 2 : [[153527, '701654', '1'], [200847, '3[]298', '0']]
Level 3 : [[150974, ' ', '1'], [150974, ',', '0'], [200847, '3[]298', '0']]
Level 4 : [[94756, '3[', '1'], [106091, ']298', '0'], [150974, ',', '0']]
Level 5 : [[70880, '701', '1'], [82647, '654', '0'], [106091, ']298', '0'], [150974, ',', '0']]
Level 6 : [[50601, ']', '1'], [55490, '298', '0'], [82647, '654', '0'], [150974, ' ', '1']]
Level 7 : [[44155, '3', '1'], [50601, '[', '0'], [55490, '298', '0'], [82647, '654', '0'], [150974, ',', '0']]
Level 8 : [[39445, '65', '1'], [43202, '4', '0'], [50601, '[', '0'], [55490, '298', '0'], [150974, ' ', '1']]
Level 9 : [[32698, '70', '1'], [38182, '1', '0'], [43202, '4', '0'], [50601, '[', '0'], [55490, '298', '0'], [150974, ',', '0']]
Level 10 : [[27375, '2', '1'], [28115, '98', '0'], [38182, '1', '0'], [43202, '4', '0'], [50601, '[', '0'], [15097

In [6]:
uncompressed_file_size = len(my_string)*7
compressed_file_size = len(binary)-2
print("Your original file size was", uncompressed_file_size,"bits. The compressed size is:",compressed_file_size)
print("This is a saving of ",uncompressed_file_size-compressed_file_size,"bits")
print("Compression Ratio: ",uncompressed_file_size/compressed_file_size)
#Bits per pixel (BPP)
print("BPP: ",compressed_file_size/num_pixels)
output = open("compressed.txt","w+")
print("Compressed file generated as compressed.txt")
output = open("compressed.txt","w+")
print("Decoding.......")

Your original file size was 4594254 bits. The compressed size is: 2177140
This is a saving of  2417114 bits
Compression Ratio:  2.110224422866697
BPP:  43.26159960258321
Compressed file generated as compressed.txt
Decoding.......


In [7]:
output.write(bitstring)

bitstring = str(binary[2:])
uncompressed_string =""
code =""
for digit in bitstring:
    code = code+digit
    pos=0                                        #iterating and decoding
    for letter in letter_binary:
        if code ==letter[1]:
            uncompressed_string=uncompressed_string+letter_binary[pos] [0]
            code=""
        pos+=1

In [8]:
print("Your UNCOMPRESSED data is:")
if h == 1:
    temp = re.findall(r'\d+', uncompressed_string)
    res = list(map(int, temp))
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, shape)
    import numpy as np
    mse = (np.square(res - a)).mean(axis=None)
    print(mse)
    print(res)
    print("Observe the shapes and input and output arrays are matching or not")
    print("Input image dimensions:",shape)
    print("Output image dimensions:",res.shape)
    data = Image.fromarray(res)
    data.save('output.png')
    if a.all() == res.all():
        print("Success")
if h == 2:
    temp = re.findall(r'\d+', uncompressed_string)
    res = list(map(int, temp))
    print(res)
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, (1024, 720))
    print(res)
    data = Image.fromarray(res)
    data.save('output.png')
    print("Success")

Your UNCOMPRESSED data is:
0.0
[[[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 ...

 [[10 10 10]
  [ 6  6  6]
  [ 3  3  3]
  ...
  [ 4  4  4]
  [ 5  5  5]
  [ 5  5  5]]

 [[10 10 10]
  [ 6  6  6]
  [ 3  3  3]
  ...
  [ 4  4  4]
  [ 5  5  5]
  [ 5  5  5]]

 [[10 10 10]
  [ 6  6  6]
  [ 3  3  3]
  ...
  [ 4  4  4]
  [ 5  5  5]
  [ 5  5  5]]]
Observe the shapes and input and output arrays are matching or not
Input image dimensions: (275, 183, 3)
Output image dimensions: (275, 183, 3)
Success
